#spring.application.name=user-service



spring:
  application:
    name: user-service
#port chay cac business service config trong file application.yml trong config server
  config:
    import: "optional:configserver:http://localhost:8083"
#cau hinh ket noi database MySQL
  datasource:
    url: "jdbc:mysql://localhost:3306/user_service"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

